# Generated by Django 6.0 on 2026-02-10 12:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_percentage', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Процент начисления')),
                ('max_points_per_use', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Максимум баллов за раз')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройка лояльности',
                'verbose_name_plural': 'Настройки лояльности',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_notifications',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sms_notifications',
        ),
        migrations.AddField(
            model_name='user',
            name='reset_password_token',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Токен сброса'),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_password_token_expires',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок токена'),
        ),
        migrations.AlterField(
            model_name='user',
            name='barcode',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='Штрих-код'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='Только буквы, пробелы и дефисы', regex='^[a-zA-Zа-яА-ЯёЁ\\s\\-]+$')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Телефон в формате: '+79999999999'", regex='^\\+7\\d{10}$')], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='user',
            name='visits_count',
            field=models.IntegerField(default=0, verbose_name='Посещений'),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итоговая сумма')),
                ('points_used', models.IntegerField(default=0, verbose_name='Использовано баллов')),
                ('points_earned', models.IntegerField(default=0, verbose_name='Начислено баллов')),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('items_summary', models.TextField(blank=True, verbose_name='Товары')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупки',
                'ordering': ['-purchase_date'],
            },
        ),
    ]
