# Generated by Django 6.0 on 2026-02-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_loyaltysettings_remove_user_email_notifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='items_detail',
            field=models.JSONField(blank=True, default=list, verbose_name='Детали товаров'),
        ),
    ]
