# Generated by Django 6.0 on 2026-01-27 21:46

import django.core.validators
import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='О нас', max_length=200, verbose_name='Заголовок страницы')),
                ('slug', models.SlugField(default='about', max_length=200, unique=True, verbose_name='URL')),
                ('main_image', models.ImageField(blank=True, help_text='Основное фото для страницы', null=True, upload_to='about/', verbose_name='Главное изображение')),
                ('show_main_image', models.BooleanField(default=True, verbose_name='Показывать главное изображение')),
                ('main_text', tinymce.models.HTMLField(blank=True, verbose_name='Основной текст')),
                ('show_main_text', models.BooleanField(default=True, verbose_name='Показывать основной текст')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, max_length=300, verbose_name='Meta Description')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Страница "О нас"',
                'verbose_name_plural': 'Страница "О нас"',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Название галереи')),
                ('description', models.TextField(blank=True, verbose_name='Описание галереи')),
                ('show_title', models.BooleanField(default=True, verbose_name='Показывать заголовок')),
                ('show_description', models.BooleanField(default=True, verbose_name='Показывать описание')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Показывать галерею')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='about.aboutpage')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галереи',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Рекомендуемый размер: 1200x800px (3:2), формат: JPEG/WebP, максимум 5MB', upload_to='about/gallery/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], message='Разрешены только файлы: JPG, JPEG, PNG, WebP')], verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Подпись')),
                ('show_caption', models.BooleanField(default=True, verbose_name='Показывать подпись')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='about.gallery')),
            ],
            options={
                'verbose_name': 'Изображение галереи',
                'verbose_name_plural': 'Изображения галереи',
                'ordering': ['display_order'],
            },
        ),
    ]
