# Generated by Django 6.0 on 2026-02-03 20:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_type', models.CharField(choices=[('drinks', 'Напитки'), ('desserts', 'Десерты'), ('sandwiches', 'Сэндвичи и выпечка')], default='drinks', max_length=20, verbose_name='Тип меню')),
                ('name', models.CharField(max_length=200, verbose_name='Название группы')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Группа товаров',
                'verbose_name_plural': 'Группы товаров',
                'ordering': ['menu_type', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL')),
                ('short_description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('composition', models.TextField(blank=True, verbose_name='Состав')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение')),
                ('is_available', models.BooleanField(default=True, verbose_name='В наличии')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемый')),
                ('show_in_menu', models.BooleanField(default=True, verbose_name='Показывать в меню')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Порядок в группе')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.productgroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['group', 'display_order', '-is_featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_name', models.CharField(blank=True, help_text='Например: Маленький, Средний, 1 порция, 100г', max_length=50, verbose_name='Название размера')),
                ('volume_value', models.CharField(help_text='Например: 250 мл, 350 мл, 100 г', max_length=50, verbose_name='Значение объема')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('calories', models.PositiveIntegerField(blank=True, help_text='Необязательно', null=True, verbose_name='Калории')),
                ('is_available', models.BooleanField(default=True, verbose_name='В наличии')),
                ('is_default', models.BooleanField(default=False, verbose_name='Вариант по умолчанию')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Вариант товара',
                'verbose_name_plural': 'Варианты товаров',
                'ordering': ['product', '-is_default'],
            },
        ),
    ]
