# Generated by Django 6.0 on 2026-01-20 13:03

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Не более 200 символов', max_length=200, verbose_name='Название акции')),
                ('slug', models.SlugField(help_text='Уникальная часть URL. Заполняется автоматически.', max_length=200, unique=True, verbose_name='URL-адрес акции')),
                ('image', models.ImageField(help_text='Рекомендуемый размер: 1200×600 пикселей.', upload_to='promotions/%Y/%m/%d/', verbose_name='Изображение акции')),
                ('description', tinymce.models.HTMLField(help_text='Полное описание акции с форматированием (макс. 500 символов)', verbose_name='Описание акции')),
                ('short_description', models.CharField(blank=True, help_text='Краткое описание для отображения в карточке (макс. 200 символов)', max_length=200, verbose_name='Краткое описание (для карточек)')),
                ('start_date', models.DateField(help_text='Когда акция начинает действовать', verbose_name='Дата начала')),
                ('end_date', models.DateField(help_text='Когда акция заканчивается', verbose_name='Дата окончания')),
                ('is_active', models.BooleanField(default=True, help_text='Отметьте, если акция активна', verbose_name='Активна')),
                ('is_featured', models.BooleanField(default=False, help_text='Выделить на главной странице', verbose_name='Популярная акция')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше в списке', verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
                'ordering': ['order', '-created_date'],
                'indexes': [models.Index(fields=['is_active', 'start_date', 'end_date'], name='promotions__is_acti_6fdf95_idx'), models.Index(fields=['slug'], name='promotions__slug_ba546d_idx')],
            },
        ),
    ]
