# Generated by Django 6.0 on 2026-01-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_add_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='short_description',
            field=models.CharField(blank=True, help_text='Краткое описание для отображения в карточке (макс. 200 символов)', max_length=200, verbose_name='Краткое описание (для карточек)'),
        ),
    ]
