# Generated by Django 6.0 on 2026-01-20 13:05

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Максимум 100 символов. Например: "Новости", "Рецепты"', max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(help_text='Уникальная часть URL для этой категории. Заполняется автоматически.', max_length=100, unique=True, verbose_name='URL-адрес категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Не более 200 символов. Будет отображаться в заголовке страницы.', max_length=200, verbose_name='Заголовок статьи')),
                ('slug', models.SlugField(help_text='Уникальная часть URL. Используется для создания читаемых ссылок.', max_length=200, unique=True, verbose_name='URL-адрес статьи')),
                ('excerpt', models.TextField(blank=True, help_text='Краткое описание для превью (до 300 символов).', max_length=300, verbose_name='Краткое описание')),
                ('content', tinymce.models.HTMLField(help_text='Основной текст статьи с форматированием. Используйте редактор выше.', verbose_name='Содержимое статьи')),
                ('image', models.ImageField(blank=True, help_text='Рекомендуемый размер: 1200×600 пикселей. Будет использоваться как превью.', null=True, upload_to='blog/%Y/%m/%d/', verbose_name='Главное изображение')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('published_date', models.DateTimeField(blank=True, help_text='Если установить дату в будущем, статья опубликуется автоматически в это время.', null=True, verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(default=False, help_text='Отметьте, чтобы статья появилась на сайте.', verbose_name='Опубликовано')),
                ('is_featured', models.BooleanField(default=False, help_text='Отметьте, чтобы выделить статью на главной странице.', verbose_name='Рекомендуемая статья')),
                ('views', models.PositiveIntegerField(default=0, editable=False, verbose_name='Количество просмотров')),
                ('meta_title', models.CharField(blank=True, help_text='Заголовок для SEO. Если не заполнен, используется обычный заголовок.', max_length=200, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, help_text='Краткое описание для поисковых систем (до 300 символов).', max_length=300, verbose_name='Meta Description')),
                ('author', models.ForeignKey(help_text='Пользователь, который создал статью.', on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('categories', models.ManyToManyField(blank=True, help_text='Выберите одну или несколько категорий для статьи.', related_name='posts', to='blog.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Статья блога',
                'verbose_name_plural': 'Статьи блога',
                'ordering': ['-published_date', '-created_date'],
                'indexes': [models.Index(fields=['-published_date', 'is_published'], name='blog_post_publish_8453cf_idx'), models.Index(fields=['slug'], name='blog_post_slug_cdb902_idx')],
            },
        ),
    ]
