# Generated by Django 6.0 on 2026-01-26 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Главная', editable=False, max_length=100, verbose_name='Для админки')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('show_carousel', models.BooleanField(default=True, verbose_name='Показывать карусель')),
                ('show_pair', models.BooleanField(default=True, verbose_name='Показывать парные картинки')),
                ('show_map', models.BooleanField(default=True, verbose_name='Показывать карту')),
                ('show_gallery', models.BooleanField(default=True, verbose_name='Показывать галерею')),
            ],
            options={
                'verbose_name': 'Главная страница',
                'verbose_name_plural': 'Главная страница',
            },
        ),
        migrations.CreateModel(
            name='HomeMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview_image', models.ImageField(blank=True, help_text='Не обязательно', null=True, upload_to='home/map/', verbose_name='Превью карты')),
                ('iframe_code', models.TextField(blank=True, help_text='HTML код из Google Maps (не обязательно)', verbose_name='Код iframe карты')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='home.homepage')),
            ],
            options={
                'verbose_name': 'Google Карта',
                'verbose_name_plural': '🗺️ Google Карта (необязательно)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomeGalleryPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, help_text='Не обязательно', null=True, upload_to='home/gallery/pair/', verbose_name='Первая картинка пары')),
                ('image2', models.ImageField(blank=True, help_text='Не обязательно', null=True, upload_to='home/gallery/pair/', verbose_name='Вторая картинка пары')),
                ('link1', models.URLField(blank=True, verbose_name='Ссылка для первой')),
                ('link2', models.URLField(blank=True, verbose_name='Ссылка для второй')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair_images', to='home.homepage')),
            ],
            options={
                'verbose_name': 'Пара картинок',
                'verbose_name_plural': '📐 Пара картинок (необязательно)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomeCarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_pc', models.ImageField(blank=True, help_text='Не обязательно', null=True, upload_to='home/carousel/pc/', verbose_name='🖥️ Для компьютера/планшета')),
                ('image_phone', models.ImageField(blank=True, help_text='Не обязательно', null=True, upload_to='home/carousel/phone/', verbose_name='📱 Для телефона')),
                ('link', models.URLField(blank=True, verbose_name='Ссылка')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel', to='home.homepage')),
            ],
            options={
                'verbose_name': 'Слайд карусели',
                'verbose_name_plural': '🎠 Карусель (необязательно)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomeAdditionalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Не обязательно', null=True, upload_to='home/gallery/additional/', verbose_name='Картинка')),
                ('link', models.URLField(blank=True, verbose_name='Ссылка')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='home.homepage')),
            ],
            options={
                'verbose_name': 'Дополнительная картинка',
                'verbose_name_plural': '➕ Дополнительные картинки (необязательно)',
                'ordering': ['order'],
            },
        ),
    ]
