# Generated by Django 6.0 on 2025-01-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='show_carousel',
            field=models.BooleanField(default=True, verbose_name='Показывать карусель'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_gallery',
            field=models.BooleanField(default=True, verbose_name='Показывать галерею'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_map',
            field=models.BooleanField(default=True, verbose_name='Показывать карту'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_pair',
            field=models.BooleanField(default=True, verbose_name='Показывать парные картинки'),
        ),
    ]