# Generated by Django 6.0 on 2026-02-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_add_show_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeadditionalimage',
            options={'ordering': ['order'], 'verbose_name': 'Дополнительная картинка', 'verbose_name_plural': 'Дополнительные картинки'},
        ),
        migrations.AlterModelOptions(
            name='homecarouselimage',
            options={'ordering': ['order'], 'verbose_name': 'Слайд карусели', 'verbose_name_plural': 'Карусель'},
        ),
        migrations.AlterModelOptions(
            name='homegallerypair',
            options={'ordering': ['order'], 'verbose_name': 'Пара картинок', 'verbose_name_plural': 'Пара картинок'},
        ),
        migrations.AlterModelOptions(
            name='homemap',
            options={'ordering': ['order'], 'verbose_name': 'Google Карта', 'verbose_name_plural': 'Google Карта'},
        ),
        migrations.AddField(
            model_name='homeadditionalimage',
            name='image_phone',
            field=models.ImageField(blank=True, help_text='Не обязательно', null=True, upload_to='home/gallery/additional/phone/', verbose_name='Картинка для телефона'),
        ),
        migrations.AddField(
            model_name='homemap',
            name='preview_image_phone',
            field=models.ImageField(blank=True, help_text='Не обязательно', null=True, upload_to='home/map/phone/', verbose_name='Превью карты для телефона'),
        ),
        migrations.AlterField(
            model_name='homeadditionalimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Не обязательно', null=True, upload_to='home/gallery/additional/pc/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='homemap',
            name='iframe_code',
            field=models.TextField(blank=True, help_text='HTML код из Google Maps', verbose_name='Код iframe карты'),
        ),
        migrations.AlterField(
            model_name='homemap',
            name='preview_image',
            field=models.ImageField(blank=True, help_text='Не обязательно', null=True, upload_to='home/map/pc/', verbose_name='Превью карты для компьютера/планшета'),
        ),
    ]
